name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test code
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: yarn install
    - name: Run tests and collect coverage
      run: npm run lint 
    - name: Upload coverage reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t "2b419733-b6f4-42c6-91e8-d814db800f91"
